server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  mvc:
    async:
      request-timeout: 0

logging:
  level:
    org.hibernate.orm.connections.pooling: warn

imagekit:
  public-key: ${IMAGEKIT_PUBLIC_KEY}
  private-key: ${IMAGEKIT_PRIVATE_KEY}
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT}

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}

email:
  mail: ${MAIL_SENDER}
  password: ${MAIL_PASSWORD}
