server.port = 8080
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true

#_____Local Database_______#
#spring.datasource.url=jdbc:postgresql://localhost:5432/trangtintuc_v4_db
#spring.datasource.username=postgres
#spring.datasource.password=redminote4
#__________________________#

#_____Avien Database_______#
spring.datasource.url=jdbc:postgresql://pg-20cb3ce-thai27webdeveloper-7dc4.l.aivencloud.com:27281/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ii6SvVDsvWLRCezHZ1c
#__________________________#


