
server.port = 8080

#_____Local Database_______#
#spring.datasource.url=jdbc:postgresql://localhost:5432/trangtintuc_v4_db
#spring.datasource.username=postgres
#spring.datasource.password=redminote4
#__________________________#

#_____Avien Database_______#
spring.datasource.url=jdbc:postgresql://pg-20cb3ce-thai27webdeveloper-7dc4.l.aivencloud.com:27281/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_qWBeh8vrGBFztsc5ke-
#__________________________#

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=FIS.auto.service@gmail.com
#spring.mail.password=qvaudviuwcblhqkq
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#FIS.auto.service pass: w3zeIKouk7aPJxT

